name: esprit
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  routemaster: ^1.0.1
  cupertino_icons: ^1.0.8
  dotted_border: ^2.0.0+2  # Added for image upload UI
  share_plus: ^7.0.0
  file_picker: ^6.1.1
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/esprit.png  # Ensure this matches your file name and path
    - assets/Esprit.jpeg
    - assets/esb.jpeg
    - assets/espritC-C.jpeg
    - assets/event.jpg