name: esprit
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'  # Spécifiez une plage pour éviter les problèmes de compatibilité future

dependencies:
  flutter:
    sdk: flutter
  routemaster: ^1.0.1
  cupertino_icons: ^1.0.8
  dotted_border: ^2.0.0+2
  url_launcher: ^6.1.11
  webview_flutter: ^4.0.7
  image_picker: ^1.0.7
  share_plus: ^7.0.2
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/esprit.png  
    - assets/Esprit.jpeg
    - assets/espritC-C.jpeg 
    - assets/esb.jpeg
    - assets/avatar.png
    - assets/event.jpg