name: esprit
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  routemaster: ^1.0.1
  cupertino_icons: ^1.0.8
  dotted_border: ^2.0.0+2
  url_launcher: ^6.1.11
  webview_flutter: ^4.4.0
  image_picker: ^1.0.7
  file_picker: ^6.1.1  # Utilisez la dernière version stable (vérifiez sur pub.dev)
  share_plus: ^7.0.0
  provider: ^6.0.0





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/esprit.png  
    - assets/espritC-C.jpeg 
    - assets/esb.jpeg
    - assets/avatar.png
    # Ensure this matches your file name and path